name: Publish docker

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@v5
                  registry: docker.pkg.github.COM
                  name: https://docker.pkg.github.com/everlynd/art-pet/art-pet
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
