name: Publish docker

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@v4
              with:
                compose-file: "./docker/docker-compose.yml"
                down-flags: "--volumes"
                services: 
                    mysql
                    nginx
                    api
                    client
                    admin
                 